source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.6'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.3'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer',  platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring',        group: :development

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]
#gem 'doop', :git => "git://github.com/coder36/doop.git"

gem "govuk_frontend_toolkit", "~> 1.6"
gem "govuk_template", "~> 0.9"
gem "jquery-ui-rails", "~> 5.0"
gem "blueimp-gallery", "~> 2.11.0"
gem "jquery-fileupload-rails", "~> 0.4"


group :production do
  gem 'rails_12factor', "~> 0.0"
  gem 'pg', "~> 0.17"
end

group :development do
  gem 'sqlite3', "~> 1.3"
  gem 'rspec-rails', "~> 3.1"
  gem 'guard-rspec', "~> 4.3"
  gem 'capybara', "~> 2.4"
  gem 'pry', "~> 0.10"
  gem 'pry-nav', "~> 0.2"
  gem 'capybara-webkit', "~> 1.3"
  gem 'headless', "~> 1.0"
  gem 'capybara-screenshot', "~> 1.0"
end

if File.exists?( "heroku")
  gem 'doop', :git => "git://github.com/coder36/doop.git"
elsif File.exists?( "../../doop" )
  gem 'doop', :path => "../"
else
  gem 'doop'
end
